import { gradeItem, gradePassage, splitEnglishSentences, wordCount } from "./scoring";
import {
  Bank,
  DetectorSpec,
  DrillItem,
  ErrorCat,
  PassageItem,
  SentenceItem,
  Trap,
  Weight,
} from "./types";

function passFor(category: ErrorCat): "A" | "B" {
  return category === "P" || category === "SP" || category === "G" || category === "IND" ? "A" : "B";
}

function trap(spec: {
  id: string;
  category: ErrorCat;
  weight: Weight;
  detector: DetectorSpec;
  comment: string;
  ok?: string;
  no?: string;
  pitfall: string;
  label: string;
  lemma?: string;
}): Trap {
  return {
    id: spec.id,
    category: spec.category,
    weightIfMissed: spec.weight,
    detector: spec.detector,
    comment: spec.comment,
    okExample: spec.ok,
    noExample: spec.no,
    pitfall: spec.pitfall,
    label: spec.label,
    lemma: spec.lemma,
    pass: passFor(spec.category),
  };
}

function micro(spec: {
  id: string;
  bank: Bank;
  spanish: string;
  english: string;
  acceptables?: string[];
  domain: string;
  level?: string;
  traps: Trap[];
}): DrillItem {
  return {
    id: spec.id,
    mode: "micro",
    bank: spec.bank,
    spanish: spec.spanish,
    english: spec.english,
    acceptables: spec.acceptables,
    domain: spec.domain,
    level: spec.level,
    focus: [...new Set(spec.traps.map((t) => t.pitfall))],
    errors_to_catch: spec.traps.map((t) => t.label),
    traps: spec.traps,
  };
}

const req = (anyOf: string[], caseSensitive = false): DetectorSpec => ({
  kind: "required_span",
  anyOf,
  caseSensitive,
});
const forbid = (anyOf: string[], caseSensitive = false): DetectorSpec => ({
  kind: "forbidden_span",
  anyOf,
  caseSensitive,
});
const caps = (no: string[]): DetectorSpec => ({ kind: "title_caps", no });

export const MICROS: DrillItem[] = [
  micro({
    id: "1",
    bank: "titles",
    domain: "political",
    level: "B2",
    spanish: "El congresista mexicano José Ramírez se reunió con el secretario de Estado.",
    english: "Mexican Congressman José Ramírez met with the Secretary of State.",
    acceptables: [
      "Congressman José Ramírez of Mexico met with the Secretary of State.",
      "Mexican Congressman Jose Ramirez met with the Secretary of State.",
    ],
    traps: [
      trap({
        id: "1-congressman-caps",
        category: "SP",
        weight: 2,
        detector: caps(["congressman"]),
        comment: "A title immediately before a name is capitalized in US English.",
        ok: "Congressman José Ramírez",
        no: "congressman José Ramírez",
        pitfall: "Lowercase title before a name",
        label: "Congressman vs congressman",
      }),
      trap({
        id: "1-secretary-caps",
        category: "SP",
        weight: 2,
        detector: caps(["secretary of state", "secretary of State"]),
        comment: "Capitalize Secretary of State when the rendering names that officeholder.",
        ok: "the Secretary of State",
        no: "the secretary of state",
        pitfall: "Secretary of State caps",
        label: "Secretary of State vs secretary",
      }),
      trap({
        id: "1-mexicano",
        category: "O",
        weight: 2,
        detector: req(["Mexican", "of Mexico", "Mexico's", "from Mexico"]),
        comment: "mexicano is in the source. If the English key keeps the nationality, dropping it is an omission.",
        ok: "Mexican Congressman",
        no: "Congressman José Ramírez met with the Secretary of State.",
        pitfall: "Dropped nationality",
        label: "Nationality mexicano dropped",
        lemma: "mexicano",
      }),
    ],
  }),
  micro({
    id: "2",
    bank: "titles",
    domain: "political",
    level: "B1",
    spanish: "El Congreso de los Estados Unidos aprobó la ley por mayoría.",
    english: "The United States Congress approved the law by majority.",
    acceptables: [
      "The U.S. Congress approved the law by a majority.",
      "The United States Congress passed the law by a majority.",
    ],
    traps: [
      trap({
        id: "2-congress-caps",
        category: "SP",
        weight: 2,
        detector: caps(["congress"]),
        comment: "The name of the legislature is capitalized: the United States Congress.",
        ok: "the United States Congress",
        no: "the united states congress",
        pitfall: "Institution caps",
        label: "Congress vs congress",
      }),
      trap({
        id: "2-us-caps",
        category: "SP",
        weight: 1,
        detector: caps(["united states"]),
        comment: "United States is a proper name. Lowercase united states is a capitalization miss.",
        ok: "the United States",
        no: "the united states",
        pitfall: "Country-name caps",
        label: "United States formatting",
      }),
    ],
  }),
  micro({
    id: "3",
    bank: "titles",
    domain: "political",
    level: "B2",
    spanish: "La senadora demócrata del estado de California criticó la propuesta republicana.",
    english: "The Democratic senator from the state of California criticized the Republican proposal.",
    acceptables: ["The Democratic senator from California criticized the Republican proposal."],
    traps: [
      trap({
        id: "3-democratic",
        category: "SP",
        weight: 2,
        detector: caps(["democratic"]),
        comment: "Party names used as adjectives stay capitalized: Democratic, not democratic.",
        ok: "The Democratic senator",
        no: "The democratic senator",
        pitfall: "Party-name caps",
        label: "Democratic vs democratic",
      }),
      trap({
        id: "3-republican",
        category: "SP",
        weight: 2,
        detector: caps(["republican"]),
        comment: "Republican is capitalized when it names the party.",
        ok: "the Republican proposal",
        no: "the republican proposal",
        pitfall: "Party-name caps",
        label: "Republican vs republican",
      }),
      trap({
        id: "3-california",
        category: "SP",
        weight: 1,
        detector: caps(["california"]),
        comment: "California is a proper name.",
        ok: "California",
        no: "california",
        pitfall: "Place-name caps",
        label: "California capitalization",
      }),
    ],
  }),
  micro({
    id: "4",
    bank: "P",
    domain: "financial",
    level: "B2",
    spanish: '"La situación es crítica", declaró el presidente del Banco Central Europeo.',
    english: '"The situation is critical," declared the president of the European Central Bank.',
    acceptables: [
      'The president of the European Central Bank declared, "The situation is critical."',
    ],
    traps: [
      trap({
        id: "4-quotes",
        category: "P",
        weight: 2,
        detector: { kind: "required_pattern", pattern: '"[^"]*[,.]"' },
        comment: "US quotation marks put the comma or period inside the closing quote.",
        ok: '"The situation is critical," declared',
        no: '"The situation is critical", declared',
        pitfall: "Comma outside the closing quote",
        label: "Quote punctuation",
      }),
      trap({
        id: "4-ecb",
        category: "O",
        weight: 4,
        detector: req(["European Central Bank", "ECB", "european central bank"]),
        comment: "The institution has to be there. Banco Central Europeo is not optional color.",
        ok: "the European Central Bank",
        pitfall: "Dropped institution",
        label: "European Central Bank omitted",
      }),
      trap({
        id: "4-ecb-caps",
        category: "SP",
        weight: 2,
        detector: caps(["european central bank"]),
        comment: "Capitalize the full name of the bank.",
        ok: "European Central Bank",
        no: "european central bank",
        pitfall: "Institution caps",
        label: "European Central Bank caps",
      }),
    ],
  }),
  micro({
    id: "5",
    bank: "titles",
    domain: "medical",
    level: "C1",
    spanish: "El doctor García, jefe del departamento de cardiología, publicó un estudio en la revista Nature.",
    english: "Dr. García, head of the cardiology department, published a study in Nature magazine.",
    acceptables: [
      "Doctor García, head of the cardiology department, published a study in Nature magazine.",
      "Dr. Garcia, head of the cardiology department, published a study in Nature.",
    ],
    traps: [
      trap({
        id: "5-dr",
        category: "SP",
        weight: 2,
        detector: caps(["dr. García", "dr. Garcia", "dr García", "dr Garcia"]),
        comment: "Dr. before a name is capitalized. The department name stays lower because it is not a proper title here.",
        ok: "Dr. García",
        no: "dr. García",
        pitfall: "Lowercase title before a name",
        label: "Dr. vs dr.",
      }),
      trap({
        id: "5-nature",
        category: "SP",
        weight: 1,
        detector: caps(["nature"]),
        comment: "Nature, the journal, is a proper name.",
        ok: "Nature magazine",
        no: "nature magazine",
        pitfall: "Publication caps",
        label: "Nature capitalization",
      }),
      trap({
        id: "5-name",
        category: "O",
        weight: 4,
        detector: req(["García", "Garcia"]),
        comment: "The person's name is missing.",
        ok: "Dr. García",
        pitfall: "Dropped name",
        label: "García omitted",
        lemma: "García",
      }),
    ],
  }),
  micro({
    id: "6",
    bank: "titles",
    domain: "academic",
    level: "B2",
    spanish: "La Universidad de Harvard y el Instituto Tecnológico de Massachusetts colaboran en el proyecto.",
    english: "Harvard University and the Massachusetts Institute of Technology are collaborating on the project.",
    acceptables: ["Harvard University and MIT are collaborating on the project."],
    traps: [
      trap({
        id: "6-calque",
        category: "U",
        weight: 2,
        detector: forbid(["University of Harvard"]),
        comment: "English usage is Harvard University. University of Harvard is a word-order calque.",
        ok: "Harvard University",
        no: "the University of Harvard",
        pitfall: "Name-order calque",
        label: "University of Harvard",
      }),
      trap({
        id: "6-harvard",
        category: "O",
        weight: 4,
        detector: req(["Harvard"]),
        comment: "Harvard is missing.",
        ok: "Harvard University",
        pitfall: "Dropped institution",
        label: "Harvard omitted",
      }),
      trap({
        id: "6-mit",
        category: "O",
        weight: 4,
        detector: { kind: "required_pattern", pattern: "Massachusetts Institute of Technology|\\bMIT\\b" },
        comment: "The Massachusetts institute is missing. MIT is an acceptable short form.",
        ok: "the Massachusetts Institute of Technology",
        pitfall: "Dropped institution",
        label: "MIT omitted",
      }),
    ],
  }),
  micro({
    id: "7",
    bank: "titles",
    domain: "religious",
    level: "B2",
    spanish: "El papa Francisco se reunió con el primer ministro italiano en el Vaticano.",
    english: "Pope Francis met with the Italian Prime Minister at the Vatican.",
    acceptables: ["Pope Francis met the Italian Prime Minister at the Vatican."],
    traps: [
      trap({
        id: "7-pope",
        category: "SP",
        weight: 2,
        detector: caps(["pope Francis", "pope francis"]),
        comment: "Pope before the name is capitalized.",
        ok: "Pope Francis",
        no: "pope Francis",
        pitfall: "Lowercase title before a name",
        label: "Pope vs pope",
      }),
      trap({
        id: "7-pm",
        category: "SP",
        weight: 1,
        detector: caps(["prime minister"]),
        comment: "The key capitalizes Prime Minister for this incumbent. Fully lowercase prime minister is a light caps miss.",
        ok: "the Italian Prime Minister",
        no: "the Italian prime minister",
        pitfall: "Officeholder caps",
        label: "Prime Minister vs prime minister",
      }),
      trap({
        id: "7-vatican",
        category: "SP",
        weight: 1,
        detector: caps(["vatican"]),
        comment: "Vatican is a proper name.",
        ok: "the Vatican",
        no: "the vatican",
        pitfall: "Place-name caps",
        label: "Vatican capitalization",
      }),
    ],
  }),
  micro({
    id: "8",
    bank: "titles",
    domain: "legal",
    level: "B2",
    spanish: "Según el artículo 23 de la Constitución española, todos los ciudadanos son iguales.",
    english: "According to Article 23 of the Spanish Constitution, all citizens are equal.",
    traps: [
      trap({
        id: "8-article",
        category: "SP",
        weight: 2,
        detector: caps(["article 23"]),
        comment: "Capitalize Article when it cites a numbered provision.",
        ok: "Article 23",
        no: "article 23",
        pitfall: "Legal-citation caps",
        label: "Article vs article",
      }),
      trap({
        id: "8-constitution",
        category: "SP",
        weight: 2,
        detector: caps(["spanish constitution"]),
        comment: "Spanish Constitution is the name of the document.",
        ok: "the Spanish Constitution",
        no: "the spanish constitution",
        pitfall: "Document caps",
        label: "Spanish Constitution caps",
      }),
      trap({
        id: "8-number",
        category: "O",
        weight: 4,
        detector: req(["23"]),
        comment: "The article number is missing.",
        ok: "Article 23",
        pitfall: "Dropped number",
        label: "Article number 23 omitted",
      }),
    ],
  }),
  micro({
    id: "9",
    bank: "P",
    domain: "business",
    level: "B2",
    spanish: "La empresa IBM anunció una inversión de 50,3 millones de dólares para el primer trimestre.",
    english: "IBM announced an investment of $50.3 million for the first quarter.",
    acceptables: [
      "IBM announced an investment of 50.3 million dollars for the first quarter.",
      "The company IBM announced an investment of $50.3 million for the first quarter.",
    ],
    traps: [
      trap({
        id: "9-decimal",
        category: "P",
        weight: 2,
        detector: forbid(["50,3"]),
        comment: "US decimals use a point: $50.3 million, not 50,3.",
        ok: "$50.3 million",
        no: "50,3 million dollars",
        pitfall: "Spanish decimal comma",
        label: "Decimal point vs comma",
      }),
      trap({
        id: "9-number",
        category: "O",
        weight: 4,
        detector: req(["50.3", "50,3"]),
        comment: "The amount is missing.",
        ok: "$50.3 million",
        pitfall: "Dropped number",
        label: "50.3 million omitted",
      }),
      trap({
        id: "9-quarter",
        category: "O",
        weight: 2,
        detector: req(["first quarter", "Q1", "1st quarter"]),
        comment: "primer trimestre is the first quarter, and it is still in the sentence.",
        ok: "the first quarter",
        pitfall: "Dropped time phrase",
        label: "first quarter omitted",
      }),
    ],
  }),
  micro({
    id: "10",
    bank: "P",
    domain: "governmental",
    level: "C1",
    spanish: '"No obstante", agregó el ministro de Economía, "la inflación del 3,2% está controlada".',
    english: '"Nevertheless," added the Minister of Economy, "the 3.2% inflation is under control."',
    acceptables: [
      'The Minister of Economy added, "Nevertheless, the 3.2% inflation is under control."',
    ],
    traps: [
      trap({
        id: "10-quotes",
        category: "P",
        weight: 2,
        detector: { kind: "required_pattern", pattern: '"[^"]*[,.]"' },
        comment: "In a split quotation the comma stays inside the quotes: \"Nevertheless,\" added.",
        ok: '"Nevertheless," added',
        no: '"Nevertheless", added',
        pitfall: "Comma outside the closing quote",
        label: "Quote interruption punctuation",
      }),
      trap({
        id: "10-percent",
        category: "P",
        weight: 2,
        detector: forbid(["3,2"]),
        comment: "US percent figures use a decimal point: 3.2%, not 3,2%.",
        ok: "3.2%",
        no: "3,2%",
        pitfall: "Spanish decimal comma",
        label: "Percentage decimal",
      }),
      trap({
        id: "10-number",
        category: "O",
        weight: 4,
        detector: req(["3.2", "3,2"]),
        comment: "The 3.2% figure is missing.",
        ok: "3.2%",
        pitfall: "Dropped number",
        label: "3.2% omitted",
      }),
      trap({
        id: "10-minister",
        category: "SP",
        weight: 2,
        detector: caps(["minister of economy"]),
        comment: "Capitalize Minister of Economy when the phrase names that official.",
        ok: "the Minister of Economy",
        no: "the minister of economy",
        pitfall: "Officeholder caps",
        label: "Minister of Economy caps",
      }),
    ],
  }),
  micro({
    id: "11",
    bank: "titles",
    domain: "legal",
    level: "C1",
    spanish: "El Tratado de Lisboa, firmado en diciembre de 2007, modificó los tratados de la Unión Europea.",
    english: "The Treaty of Lisbon, signed in December 2007, amended the treaties of the European Union.",
    traps: [
      trap({
        id: "11-treaty",
        category: "SP",
        weight: 2,
        detector: caps(["treaty of lisbon"]),
        comment: "Treaty of Lisbon is the document's name.",
        ok: "the Treaty of Lisbon",
        no: "the treaty of lisbon",
        pitfall: "Document caps",
        label: "Treaty capitalization",
      }),
      trap({
        id: "11-lisboa",
        category: "U",
        weight: 2,
        detector: forbid(["Lisboa", "lisboa"]),
        comment: "The English name of the city in this treaty title is Lisbon.",
        ok: "Treaty of Lisbon",
        no: "Treaty of Lisboa",
        pitfall: "Spanish place name left in English",
        label: "Lisbon vs Lisboa",
      }),
      trap({
        id: "11-december",
        category: "SP",
        weight: 1,
        detector: caps(["december"]),
        comment: "Month names are capitalized in US English.",
        ok: "December 2007",
        no: "december 2007",
        pitfall: "Month caps",
        label: "December capitalization",
      }),
      trap({
        id: "11-year",
        category: "O",
        weight: 4,
        detector: req(["2007"]),
        comment: "The year 2007 is missing.",
        ok: "December 2007",
        pitfall: "Dropped date",
        label: "2007 omitted",
      }),
      trap({
        id: "11-eu",
        category: "SP",
        weight: 1,
        detector: caps(["european union"]),
        comment: "European Union is a proper name.",
        ok: "the European Union",
        no: "the european union",
        pitfall: "Institution caps",
        label: "European Union formatting",
      }),
    ],
  }),
  micro({
    id: "12",
    bank: "titles",
    domain: "medical",
    level: "B2",
    spanish: "La Organización Mundial de la Salud (OMS) publicó nuevas directrices sobre la covid-19.",
    english: "The World Health Organization (WHO) published new guidelines on COVID-19.",
    acceptables: [
      "The World Health Organization published new guidelines on COVID-19.",
      "WHO published new guidelines on COVID-19.",
    ],
    traps: [
      trap({
        id: "12-oms",
        category: "U",
        weight: 2,
        detector: { kind: "forbidden_pattern", pattern: "\\bOMS\\b" },
        comment: "The English acronym is WHO. OMS is the Spanish abbreviation and does not belong in the English.",
        ok: "WHO",
        no: "OMS",
        pitfall: "Spanish acronym left in English",
        label: "WHO vs OMS",
      }),
      trap({
        id: "12-who",
        category: "O",
        weight: 4,
        detector: { kind: "required_pattern", pattern: "\\bWHO\\b|\\bOMS\\b|World Health Organization" },
        comment: "The organization is missing.",
        ok: "the World Health Organization (WHO)",
        pitfall: "Dropped institution",
        label: "World Health Organization omitted",
      }),
      trap({
        id: "12-covid",
        category: "SP",
        weight: 2,
        detector: caps(["covid-19"]),
        comment: "The disease name is COVID-19, with those capitals and the hyphen.",
        ok: "COVID-19",
        no: "covid-19",
        pitfall: "Disease-name caps",
        label: "COVID-19 vs covid-19",
      }),
      trap({
        id: "12-covid-present",
        category: "O",
        weight: 4,
        detector: req(["COVID-19", "Covid-19", "covid-19"]),
        comment: "COVID-19 is missing.",
        ok: "COVID-19",
        pitfall: "Dropped disease name",
        label: "COVID-19 omitted",
      }),
    ],
  }),
  micro({
    id: "13",
    bank: "titles",
    domain: "legal",
    level: "C1",
    spanish: "El juez Smith del Tribunal Supremo de Justicia dictó sentencia el martes pasado.",
    english: "Justice Smith of the Supreme Court of Justice handed down the ruling last Tuesday.",
    acceptables: ["Justice Smith of the Supreme Court handed down the ruling last Tuesday."],
    traps: [
      trap({
        id: "13-judge",
        category: "U",
        weight: 2,
        detector: forbid(["Judge Smith", "judge Smith"]),
        comment: "A member of a supreme court is Justice Smith in US usage, not Judge Smith.",
        ok: "Justice Smith",
        no: "Judge Smith",
        pitfall: "Judge used for a justice",
        label: "Justice vs Judge",
      }),
      trap({
        id: "13-justice-caps",
        category: "SP",
        weight: 2,
        detector: caps(["justice Smith", "justice smith"]),
        comment: "Justice before the name takes a capital.",
        ok: "Justice Smith",
        no: "justice Smith",
        pitfall: "Lowercase title before a name",
        label: "Justice capitalization",
      }),
      trap({
        id: "13-court",
        category: "SP",
        weight: 1,
        detector: caps(["supreme court"]),
        comment: "Supreme Court is capitalized as the name of the court.",
        ok: "the Supreme Court",
        no: "the supreme court",
        pitfall: "Court caps",
        label: "Supreme Court formatting",
      }),
      trap({
        id: "13-tuesday",
        category: "SP",
        weight: 1,
        detector: caps(["tuesday"]),
        comment: "Weekday names are capitalized.",
        ok: "Tuesday",
        no: "tuesday",
        pitfall: "Weekday caps",
        label: "Tuesday capitalization",
      }),
    ],
  }),
  micro({
    id: "14",
    bank: "titles",
    domain: "historical",
    level: "B1",
    spanish: "La guerra de Vietnam terminó en abril de 1975, según los historiadores.",
    english: "The Vietnam War ended in April 1975, according to historians.",
    acceptables: ["The Vietnam War ended in April 1975, historians say."],
    traps: [
      trap({
        id: "14-war-caps",
        category: "SP",
        weight: 2,
        detector: caps(["vietnam war"]),
        comment: "Vietnam War is the English name. Both words are capitalized.",
        ok: "the Vietnam War",
        no: "the vietnam war",
        pitfall: "War-name caps",
        label: "Vietnam War capitalization",
      }),
      trap({
        id: "14-calque",
        category: "U",
        weight: 2,
        detector: forbid(["war of Vietnam", "war of vietnam"]),
        comment: "war of Vietnam copies the Spanish word order. The US name is the Vietnam War.",
        ok: "the Vietnam War",
        no: "the war of Vietnam",
        pitfall: "Name-order calque",
        label: "Vietnam War vs war of Vietnam",
      }),
      trap({
        id: "14-april",
        category: "SP",
        weight: 1,
        detector: caps(["april"]),
        comment: "Month names are capitalized.",
        ok: "April 1975",
        no: "april 1975",
        pitfall: "Month caps",
        label: "April capitalization",
      }),
      trap({
        id: "14-year",
        category: "O",
        weight: 4,
        detector: req(["1975"]),
        comment: "The year is missing.",
        ok: "April 1975",
        pitfall: "Dropped date",
        label: "1975 omitted",
      }),
    ],
  }),
  micro({
    id: "15",
    bank: "titles",
    domain: "business",
    level: "B2",
    spanish: "El presidente ejecutivo de Microsoft, Satya Nadella, anunció una nueva estrategia.",
    english: "Microsoft CEO Satya Nadella announced a new strategy.",
    acceptables: [
      "Satya Nadella, CEO of Microsoft, announced a new strategy.",
      "Microsoft chief executive Satya Nadella announced a new strategy.",
      "Satya Nadella, chief executive of Microsoft, announced a new strategy.",
    ],
    traps: [
      trap({
        id: "15-calque",
        category: "U",
        weight: 2,
        detector: forbid(["president executive", "executive president", "President Executive"]),
        comment: "presidente ejecutivo is CEO or chief executive, not president executive.",
        ok: "Microsoft CEO Satya Nadella",
        no: "Microsoft's president executive Satya Nadella",
        pitfall: "Title calque",
        label: "CEO vs president executive",
      }),
      trap({
        id: "15-role",
        category: "O",
        weight: 2,
        detector: req(["CEO", "chief executive", "Chief Executive"]),
        comment: "The executive role is missing.",
        ok: "CEO",
        pitfall: "Dropped title",
        label: "CEO omitted",
      }),
      trap({
        id: "15-name",
        category: "O",
        weight: 4,
        detector: req(["Nadella"]),
        comment: "Satya Nadella's name is missing.",
        ok: "Satya Nadella",
        pitfall: "Dropped name",
        label: "Nadella omitted",
        lemma: "Nadella",
      }),
    ],
  }),

  micro({
    id: "pos-compromiso",
    bank: "POS",
    domain: "general",
    level: "C1",
    spanish: "Un compromiso con la vida",
    english: "A commitment to life",
    acceptables: ["A commitment to life.", "Commitment to Life", "Commitment to life"],
    traps: [
      trap({
        id: "pos-compromiso-job",
        category: "T",
        weight: 4,
        detector: {
          kind: "pos_job",
          job: "noun",
          accept: ["commitment"],
          reject: ["committed", "committing"],
        },
        comment:
          "Spanish compromiso is a noun (un compromiso). Committed to life makes the head an adjective or participle, so the grammatical job changes. Graders mark that as transfer.",
        ok: "A commitment to life",
        no: "Committed to life",
        pitfall: "POS drift on noun heads",
        label: "Noun compromiso rendered as adjective Committed",
        lemma: "compromiso",
      }),
      trap({
        id: "pos-compromiso-head",
        category: "O",
        weight: 4,
        detector: req(["commitment", "committed", "committing", "pledge", "dedication"]),
        comment: "The noun compromiso is missing, and no rendering of that idea is in the English.",
        ok: "A commitment to life",
        pitfall: "Dropped noun head",
        label: "compromiso omitted",
        lemma: "compromiso",
      }),
      trap({
        id: "pos-compromiso-life",
        category: "O",
        weight: 4,
        detector: req(["life", "living"]),
        comment: "con la vida is missing.",
        ok: "to life",
        pitfall: "Dropped complement",
        label: "vida omitted",
      }),
    ],
  }),
  micro({
    id: "pos-compromiso-title",
    bank: "POS",
    domain: "general",
    level: "C1",
    spanish: "Compromiso con la educación",
    english: "Commitment to Education",
    acceptables: ["A Commitment to Education", "Commitment to education"],
    traps: [
      trap({
        id: "pos-compromiso-title-job",
        category: "T",
        weight: 8,
        detector: {
          kind: "pos_job",
          job: "title-noun",
          accept: ["commitment"],
          reject: ["committed", "committing"],
        },
        comment:
          "This is a title. The Spanish head is a noun. Committed to Education changes the job and the register of the title.",
        ok: "Commitment to Education",
        no: "Committed to Education",
        pitfall: "POS drift on noun heads",
        label: "Title noun compromiso rendered as Committed",
        lemma: "compromiso",
      }),
      trap({
        id: "pos-compromiso-title-head",
        category: "O",
        weight: 4,
        detector: req(["commitment", "committed", "committing", "pledge"]),
        comment: "The title's noun is missing.",
        ok: "Commitment to Education",
        pitfall: "Dropped noun head",
        label: "Title compromiso omitted",
        lemma: "compromiso",
      }),
    ],
  }),
  micro({
    id: "pos-amenaza",
    bank: "POS",
    domain: "general",
    level: "B2",
    spanish: "Es una amenaza constante para el acuerdo.",
    english: "It is a constant threat to the agreement.",
    acceptables: ["It is a standing threat to the agreement."],
    traps: [
      trap({
        id: "pos-amenaza-job",
        category: "T",
        weight: 4,
        detector: {
          kind: "pos_job",
          job: "noun",
          accept: ["threat"],
          reject: ["threatening"],
        },
        comment: "amenaza is a noun. threatening turns it into a participle and changes the job.",
        ok: "a constant threat",
        no: "constantly threatening",
        pitfall: "POS drift on noun heads",
        label: "Noun amenaza rendered as threatening",
        lemma: "amenaza",
      }),
      trap({
        id: "pos-amenaza-head",
        category: "O",
        weight: 4,
        detector: req(["threat", "threatening"]),
        comment: "amenaza is missing.",
        ok: "a threat",
        pitfall: "Dropped noun head",
        label: "amenaza omitted",
        lemma: "amenaza",
      }),
    ],
  }),
  micro({
    id: "pos-decision",
    bank: "POS",
    domain: "general",
    level: "B2",
    spanish: "La decisión final fue aplazar el voto.",
    english: "The final decision was to postpone the vote.",
    acceptables: ["The final decision was to delay the vote."],
    traps: [
      trap({
        id: "pos-decision-job",
        category: "T",
        weight: 4,
        detector: {
          kind: "pos_job",
          job: "noun",
          accept: ["decision"],
          reject: ["decided", "deciding"],
        },
        comment: "decisión is a noun and English can keep it. decided / deciding changes the job.",
        ok: "The final decision was to postpone the vote.",
        no: "They finally decided to postpone the vote.",
        pitfall: "POS drift on noun heads",
        label: "Noun decisión rendered as a verb",
        lemma: "decisión",
      }),
      trap({
        id: "pos-decision-head",
        category: "O",
        weight: 4,
        detector: req(["decision", "decided", "deciding"]),
        comment: "decisión is missing.",
        ok: "the final decision",
        pitfall: "Dropped noun head",
        label: "decisión omitted",
        lemma: "decisión",
      }),
    ],
  }),
  micro({
    id: "pos-inversion",
    bank: "POS",
    domain: "business",
    level: "B2",
    spanish: "La inversión en educación cayó el año pasado.",
    english: "Investment in education fell last year.",
    acceptables: ["Education investment fell last year."],
    traps: [
      trap({
        id: "pos-inversion-job",
        category: "T",
        weight: 4,
        detector: {
          kind: "pos_job",
          job: "noun",
          accept: ["investment"],
          reject: ["investing"],
        },
        comment: "inversión is a noun. Investing in education fell keeps a gerund where the noun is natural.",
        ok: "Investment in education fell last year.",
        no: "Investing in education fell last year.",
        pitfall: "POS drift on noun heads",
        label: "Noun inversión rendered as investing",
        lemma: "inversión",
      }),
      trap({
        id: "pos-inversion-head",
        category: "O",
        weight: 4,
        detector: req(["investment", "investing"]),
        comment: "inversión is missing.",
        ok: "Investment in education",
        pitfall: "Dropped noun head",
        label: "inversión omitted",
        lemma: "inversión",
      }),
    ],
  }),
  micro({
    id: "pos-apoyo",
    bank: "POS",
    domain: "general",
    level: "B2",
    spanish: "El apoyo de la comunidad fue decisivo.",
    english: "Community support was decisive.",
    acceptables: ["The community's support was decisive.", "Support from the community was decisive."],
    traps: [
      trap({
        id: "pos-apoyo-job",
        category: "T",
        weight: 4,
        detector: {
          kind: "pos_job",
          job: "noun",
          accept: ["support"],
          reject: ["supportive"],
        },
        comment: "apoyo is a noun. supportive is an adjective and changes the job.",
        ok: "Community support was decisive.",
        no: "The community was supportive, which was decisive.",
        pitfall: "POS drift on noun heads",
        label: "Noun apoyo rendered as supportive",
        lemma: "apoyo",
      }),
      trap({
        id: "pos-apoyo-head",
        category: "O",
        weight: 4,
        detector: req(["support", "supportive", "backing"]),
        comment: "apoyo is missing.",
        ok: "community support",
        pitfall: "Dropped noun head",
        label: "apoyo omitted",
        lemma: "apoyo",
      }),
    ],
  }),
  micro({
    id: "pos-resistencia",
    bank: "POS",
    domain: "general",
    level: "B2",
    spanish: "La resistencia al cambio frenó la reforma.",
    english: "Resistance to change slowed the reform.",
    acceptables: ["Resistance to change held the reform back."],
    traps: [
      trap({
        id: "pos-resistencia-job",
        category: "T",
        weight: 4,
        detector: {
          kind: "pos_job",
          job: "noun",
          accept: ["resistance"],
          reject: ["resisting"],
        },
        comment: "resistencia is a noun. Resisting change slowed the reform swaps in a gerund.",
        ok: "Resistance to change slowed the reform.",
        no: "Resisting change slowed the reform.",
        pitfall: "POS drift on noun heads",
        label: "Noun resistencia rendered as resisting",
        lemma: "resistencia",
      }),
      trap({
        id: "pos-resistencia-head",
        category: "O",
        weight: 4,
        detector: req(["resistance", "resisting"]),
        comment: "resistencia is missing.",
        ok: "Resistance to change",
        pitfall: "Dropped noun head",
        label: "resistencia omitted",
        lemma: "resistencia",
      }),
    ],
  }),
  micro({
    id: "pos-participacion",
    bank: "POS",
    domain: "general",
    level: "B2",
    spanish: "Su participación en el debate cambió el resultado.",
    english: "Her participation in the debate changed the result.",
    acceptables: [
      "His participation in the debate changed the outcome.",
      "Their participation in the debate changed the result.",
    ],
    traps: [
      trap({
        id: "pos-participacion-job",
        category: "T",
        weight: 4,
        detector: {
          kind: "pos_job",
          job: "noun",
          accept: ["participation"],
          reject: ["participating"],
        },
        comment: "participación is a noun. Participating in the debate changed the result changes the job.",
        ok: "Her participation in the debate changed the result.",
        no: "Participating in the debate changed the result.",
        pitfall: "POS drift on noun heads",
        label: "Noun participación rendered as participating",
        lemma: "participación",
      }),
      trap({
        id: "pos-participacion-head",
        category: "O",
        weight: 4,
        detector: req(["participation", "participating"]),
        comment: "participación is missing.",
        ok: "her participation",
        pitfall: "Dropped noun head",
        label: "participación omitted",
        lemma: "participación",
      }),
    ],
  }),
  micro({
    id: "pos-proteccion",
    bank: "POS",
    domain: "general",
    level: "B2",
    spanish: "La protección de los datos es obligatoria.",
    english: "Data protection is mandatory.",
    acceptables: ["The protection of the data is mandatory.", "Protection of data is required."],
    traps: [
      trap({
        id: "pos-proteccion-job",
        category: "T",
        weight: 4,
        detector: {
          kind: "pos_job",
          job: "noun",
          accept: ["protection"],
          reject: ["protecting"],
        },
        comment: "protección is a noun. Protecting the data is mandatory changes the job.",
        ok: "Data protection is mandatory.",
        no: "Protecting the data is mandatory.",
        pitfall: "POS drift on noun heads",
        label: "Noun protección rendered as protecting",
        lemma: "protección",
      }),
      trap({
        id: "pos-proteccion-head",
        category: "O",
        weight: 4,
        detector: req(["protection", "protecting"]),
        comment: "protección is missing.",
        ok: "data protection",
        pitfall: "Dropped noun head",
        label: "protección omitted",
        lemma: "protección",
      }),
    ],
  }),
  micro({
    id: "pos-realizar",
    bank: "POS",
    domain: "general",
    level: "B2",
    spanish: "El equipo realizó una encuesta entre los pasajeros.",
    english: "The team conducted a survey of the passengers.",
    acceptables: [
      "The team carried out a survey among the passengers.",
      "The team ran a survey of passengers.",
    ],
    traps: [
      trap({
        id: "pos-realizar-cognate",
        category: "T",
        weight: 4,
        detector: forbid(["realized a survey", "realised a survey", "realized a poll"]),
        comment: "realizar is not realize. The team conducted or carried out a survey.",
        ok: "conducted a survey",
        no: "realized a survey",
        pitfall: "False friend realizar",
        label: "realizar rendered as realize",
        lemma: "realizar",
      }),
      trap({
        id: "pos-realizar-survey",
        category: "O",
        weight: 4,
        detector: req(["survey", "poll"]),
        comment: "encuesta is missing.",
        ok: "a survey",
        pitfall: "Dropped object",
        label: "encuesta omitted",
      }),
    ],
  }),
  micro({
    id: "pos-sensible",
    bank: "POS",
    domain: "technical",
    level: "B2",
    spanish: "El instrumento es muy sensible a la humedad.",
    english: "The instrument is very sensitive to humidity.",
    acceptables: ["The device is highly sensitive to humidity."],
    traps: [
      trap({
        id: "pos-sensible-cognate",
        category: "T",
        weight: 8,
        detector: { kind: "forbidden_pattern", pattern: "\\bsensible\\b", flags: "i" },
        comment: "Spanish sensible means sensitive. English sensible means reasonable, which changes the claim.",
        ok: "very sensitive",
        no: "very sensible",
        pitfall: "False friend sensible",
        label: "sensible vs sensitive",
        lemma: "sensible",
      }),
      trap({
        id: "pos-sensible-present",
        category: "O",
        weight: 4,
        detector: req(["sensitive", "sensible"]),
        comment: "The quality sensible/sensitive is missing.",
        ok: "sensitive to humidity",
        pitfall: "Dropped modifier",
        label: "sensible omitted",
        lemma: "sensible",
      }),
    ],
  }),
  micro({
    id: "pos-said",
    bank: "POS",
    domain: "journalistic",
    level: "C1",
    spanish: "Dijo la ministra que el plan sigue en vigor.",
    english: "The minister said the plan remains in force.",
    acceptables: [
      "The minister said that the plan remains in effect.",
      "The minister said the plan is still in force.",
    ],
    traps: [
      trap({
        id: "pos-said-inversion",
        category: "U",
        weight: 4,
        detector: { kind: "forbidden_pattern", pattern: "^\\s*Said the minister\\b|\\bsaid the minister that\\b", flags: "i" },
        comment: "Said the minister that… copies Spanish news syntax. US prose puts the subject first: The minister said.",
        ok: "The minister said the plan remains in force.",
        no: "Said the minister that the plan remains in force.",
        pitfall: "said-teacher inversion",
        label: "said the minister inversion",
        lemma: "dijo",
      }),
      trap({
        id: "pos-said-minister",
        category: "O",
        weight: 4,
        detector: req(["minister"]),
        comment: "The minister is missing.",
        ok: "The minister said",
        pitfall: "Dropped speaker",
        label: "ministra omitted",
      }),
    ],
  }),
  micro({
    id: "pos-actualmente",
    bank: "POS",
    domain: "general",
    level: "B1",
    spanish: "Actualmente el puente está cerrado.",
    english: "The bridge is currently closed.",
    acceptables: ["The bridge is closed at present.", "Right now the bridge is closed."],
    traps: [
      trap({
        id: "pos-actualmente-cognate",
        category: "T",
        weight: 8,
        detector: { kind: "forbidden_pattern", pattern: "\\bactually\\b", flags: "i" },
        comment: "actualmente means currently or at present. actually flips the meaning.",
        ok: "currently closed",
        no: "actually closed",
        pitfall: "False friend actualmente",
        label: "actualmente rendered as actually",
        lemma: "actualmente",
      }),
      trap({
        id: "pos-actualmente-present",
        category: "O",
        weight: 2,
        detector: req(["currently", "at present", "right now", "now", "actually"]),
        comment: "actualmente is an adverb of time. Dropping it is a small omission.",
        ok: "currently closed",
        pitfall: "Dropped intensifier",
        label: "actualmente omitted",
        lemma: "actualmente",
      }),
    ],
  }),

  micro({
    id: "o-incluso",
    bank: "O",
    domain: "general",
    level: "B2",
    spanish: "Incluso los niños participaron en la votación.",
    english: "Even the children took part in the vote.",
    acceptables: ["Even children participated in the voting.", "The children also took part in the vote."],
    traps: [
      trap({
        id: "o-incluso-drop",
        category: "O",
        weight: 2,
        detector: req(["even", "also", "too", "as well"]),
        comment: "incluso is the point of the sentence. Even / also has to survive.",
        ok: "Even the children took part in the vote.",
        no: "The children took part in the vote.",
        pitfall: "Dropped intensifier",
        label: "incluso dropped",
        lemma: "incluso",
      }),
    ],
  }),
  micro({
    id: "o-muy",
    bank: "O",
    domain: "general",
    level: "B1",
    spanish: "El riesgo sanitario es muy alto.",
    english: "The health risk is very high.",
    acceptables: ["The public-health risk is extremely high."],
    traps: [
      trap({
        id: "o-muy-drop",
        category: "O",
        weight: 2,
        detector: req(["very", "extremely", "highly"]),
        comment: "muy is small, and it is still meaning. Very / extremely has to stay.",
        ok: "very high",
        no: "The health risk is high.",
        pitfall: "Dropped intensifier",
        label: "muy dropped",
        lemma: "muy",
      }),
    ],
  }),
  micro({
    id: "o-casi",
    bank: "O",
    domain: "general",
    level: "B2",
    spanish: "Casi todos los estados firmaron el acuerdo.",
    english: "Almost all the states signed the agreement.",
    acceptables: ["Nearly every state signed the agreement."],
    traps: [
      trap({
        id: "o-casi-drop",
        category: "O",
        weight: 4,
        detector: req(["almost", "nearly"]),
        comment: "casi changes the quantity. All the states signed is a different claim.",
        ok: "Almost all the states signed the agreement.",
        no: "All the states signed the agreement.",
        pitfall: "Dropped quantifier",
        label: "casi dropped",
        lemma: "casi",
      }),
    ],
  }),
  micro({
    id: "o-paren",
    bank: "O",
    domain: "economic",
    level: "B2",
    spanish: "El PIB (producto interno bruto) creció en 2024.",
    english: "GDP (gross domestic product) grew in 2024.",
    acceptables: ["Gross domestic product (GDP) grew in 2024."],
    traps: [
      trap({
        id: "o-paren-drop",
        category: "O",
        weight: 2,
        detector: req(["gross domestic product"]),
        comment: "The parenthetical definition is in the source. Dropping it is an omission.",
        ok: "GDP (gross domestic product)",
        no: "GDP grew in 2024.",
        pitfall: "Dropped parenthetical",
        label: "Parenthetical producto interno bruto dropped",
      }),
      trap({
        id: "o-paren-year",
        category: "O",
        weight: 4,
        detector: req(["2024"]),
        comment: "The year is missing.",
        ok: "in 2024",
        pitfall: "Dropped date",
        label: "2024 omitted",
      }),
    ],
  }),
  micro({
    id: "o-list",
    bank: "O",
    domain: "general",
    level: "B1",
    spanish: "Trajo pan, leche y huevos.",
    english: "She brought bread, milk, and eggs.",
    acceptables: ["He brought bread, milk, and eggs."],
    traps: [
      trap({
        id: "o-list-bread",
        category: "O",
        weight: 4,
        detector: req(["bread"]),
        comment: "A list item is missing: pan / bread.",
        ok: "bread, milk, and eggs",
        pitfall: "Dropped list item",
        label: "pan omitted",
      }),
      trap({
        id: "o-list-milk",
        category: "O",
        weight: 4,
        detector: req(["milk"]),
        comment: "A list item is missing: leche / milk.",
        ok: "bread, milk, and eggs",
        pitfall: "Dropped list item",
        label: "leche omitted",
      }),
      trap({
        id: "o-list-eggs",
        category: "O",
        weight: 4,
        detector: req(["eggs"]),
        comment: "A list item is missing: huevos / eggs.",
        ok: "bread, milk, and eggs",
        pitfall: "Dropped list item",
        label: "huevos omitted",
      }),
    ],
  }),
  micro({
    id: "o-date",
    bank: "O",
    domain: "legal",
    level: "B2",
    spanish: "El acuerdo se firmó el 5 de marzo de 2019.",
    english: "The agreement was signed on March 5, 2019.",
    acceptables: ["The agreement was signed on 5 March 2019."],
    traps: [
      trap({
        id: "o-date-year",
        category: "O",
        weight: 4,
        detector: req(["2019"]),
        comment: "The year is missing.",
        ok: "March 5, 2019",
        pitfall: "Dropped date",
        label: "2019 omitted",
      }),
      trap({
        id: "o-date-month",
        category: "O",
        weight: 2,
        detector: req(["March", "marzo"]),
        comment: "The month is missing.",
        ok: "March 5",
        pitfall: "Dropped date",
        label: "March omitted",
      }),
      trap({
        id: "o-date-day",
        category: "O",
        weight: 2,
        detector: req(["5"]),
        comment: "The day of the month is missing.",
        ok: "March 5",
        pitfall: "Dropped date",
        label: "Day 5 omitted",
      }),
    ],
  }),
  micro({
    id: "o-name",
    bank: "O",
    domain: "political",
    level: "B2",
    spanish: "La alcaldesa Claudia López anunció el plan.",
    english: "Mayor Claudia López announced the plan.",
    acceptables: ["Mayor Claudia Lopez announced the plan."],
    traps: [
      trap({
        id: "o-name-lopez",
        category: "O",
        weight: 8,
        detector: req(["López", "Lopez"]),
        comment: "The name is missing. A title without the person is not the same sentence.",
        ok: "Mayor Claudia López",
        no: "The mayor announced the plan.",
        pitfall: "Dropped name",
        label: "Claudia López omitted",
        lemma: "López",
      }),
      trap({
        id: "o-name-mayor",
        category: "SP",
        weight: 2,
        detector: caps(["mayor Claudia", "mayor Lopez", "mayor López"]),
        comment: "Mayor before the name is capitalized.",
        ok: "Mayor Claudia López",
        no: "mayor Claudia López",
        pitfall: "Lowercase title before a name",
        label: "Mayor vs mayor",
      }),
    ],
  }),
  micro({
    id: "o-1250",
    bank: "O",
    domain: "general",
    level: "B2",
    spanish: "Asistieron 1.250 personas.",
    english: "1,250 people attended.",
    acceptables: ["There were 1,250 people in attendance.", "1250 people attended."],
    traps: [
      trap({
        id: "o-1250-distort",
        category: "T",
        weight: 8,
        detector: forbid(["1.250"]),
        comment: "1.250 in English is twelve point two five, not one thousand two hundred fifty. The separator changed the number.",
        ok: "1,250 people",
        no: "1.250 people",
        pitfall: "Thousands separator changed the value",
        label: "1.250 read as a decimal",
      }),
      trap({
        id: "o-1250-present",
        category: "O",
        weight: 8,
        detector: req(["1,250", "1250", "1.250", "one thousand two hundred fifty"]),
        comment: "The number of people is missing.",
        ok: "1,250",
        pitfall: "Dropped number",
        label: "1,250 omitted",
      }),
    ],
  }),
  micro({
    id: "o-heading",
    bank: "O",
    domain: "administrative",
    level: "B1",
    spanish: "Informe anual de gestión",
    english: "Annual Management Report",
    acceptables: ["Annual management report", "Annual performance report"],
    traps: [
      trap({
        id: "o-heading-annual",
        category: "O",
        weight: 2,
        detector: req(["annual", "yearly"]),
        comment: "anual is part of the heading. Management report without annual drops it.",
        ok: "Annual Management Report",
        no: "Management Report",
        pitfall: "Dropped heading word",
        label: "anual dropped from the heading",
        lemma: "anual",
      }),
      trap({
        id: "o-heading-report",
        category: "O",
        weight: 4,
        detector: req(["report"]),
        comment: "informe is the head of the heading.",
        ok: "Annual Management Report",
        pitfall: "Dropped heading",
        label: "informe omitted",
      }),
    ],
  }),
  micro({
    id: "o-polarity",
    bank: "O",
    domain: "political",
    level: "B2",
    spanish: "El Senado no aprobó la reforma.",
    english: "The Senate did not approve the reform.",
    acceptables: ["The Senate rejected the reform.", "The Senate did not pass the reform."],
    traps: [
      trap({
        id: "o-polarity-flip",
        category: "T",
        weight: 8,
        detector: { kind: "forbidden_pattern", pattern: "\\bSenate\\s+(approved|passed|approves)\\b", flags: "i" },
        comment: "no aprobó is negative. The Senate approved the reform flips the polarity.",
        ok: "The Senate did not approve the reform.",
        no: "The Senate approved the reform.",
        pitfall: "Polarity flip",
        label: "no aprobó flipped to approved",
      }),
      trap({
        id: "o-polarity-present",
        category: "O",
        weight: 8,
        detector: req([
          "not approve",
          "didn't approve",
          "did not approve",
          "rejected",
          "did not pass",
          "voted down",
          "failed to approve",
          "senate approved",
          "senate passed",
        ]),
        comment: "The Senate's action on the reform is missing.",
        ok: "did not approve the reform",
        pitfall: "Dropped clause",
        label: "Senate action omitted",
      }),
    ],
  }),
  micro({
    id: "o-not-only",
    bank: "O",
    domain: "economic",
    level: "C1",
    spanish: "No solo aumentó el precio, sino también la demanda.",
    english: "Not only did the price rise, but demand did too.",
    acceptables: ["Both the price and demand rose.", "The price rose, and so did demand."],
    traps: [
      trap({
        id: "o-not-only-scope",
        category: "O",
        weight: 4,
        detector: req(["not only", "both", "so did", "as well", "too"]),
        comment: "no solo… sino también says both things rose. The price rose drops the second claim's link.",
        ok: "Not only did the price rise, but demand did too.",
        no: "The price rose.",
        pitfall: "Dropped correlative",
        label: "no solo / sino también dropped",
        lemma: "no solo",
      }),
      trap({
        id: "o-not-only-demand",
        category: "O",
        weight: 4,
        detector: req(["demand"]),
        comment: "la demanda is the second half of the claim.",
        ok: "demand did too",
        pitfall: "Dropped list item",
        label: "demanda omitted",
      }),
    ],
  }),
  micro({
    id: "o-rate",
    bank: "O",
    domain: "economic",
    level: "B2",
    spanish: "La tasa de interés (4,5%) se mantuvo estable.",
    english: "The interest rate (4.5%) held steady.",
    acceptables: ["The interest rate (4.5 percent) stayed stable."],
    traps: [
      trap({
        id: "o-rate-figure",
        category: "O",
        weight: 4,
        detector: req(["4.5", "4,5"]),
        comment: "The parenthetical figure is missing.",
        ok: "The interest rate (4.5%)",
        no: "The interest rate held steady.",
        pitfall: "Dropped parenthetical",
        label: "4.5% parenthetical dropped",
      }),
      trap({
        id: "o-rate-comma",
        category: "P",
        weight: 2,
        detector: forbid(["4,5"]),
        comment: "US decimals use a point: 4.5%, not 4,5%.",
        ok: "4.5%",
        no: "4,5%",
        pitfall: "Spanish decimal comma",
        label: "4,5% decimal comma",
      }),
    ],
  }),

  micro({
    id: "p-splice",
    bank: "P",
    domain: "general",
    level: "B2",
    spanish: "Llovió mucho, cancelaron el partido.",
    english: "It rained hard, so they canceled the game.",
    acceptables: [
      "It rained hard; they canceled the game.",
      "Because it rained hard, they canceled the game.",
      "It rained hard. They canceled the game.",
    ],
    traps: [
      trap({
        id: "p-splice-hit",
        category: "P",
        weight: 2,
        detector: { kind: "forbidden_pattern", pattern: "\\brained hard,\\s+they\\b", flags: "i" },
        comment: "Two independent clauses cannot share only a comma. Use so, a semicolon, or a period.",
        ok: "It rained hard, so they canceled the game.",
        no: "It rained hard, they canceled the game.",
        pitfall: "Comma splice",
        label: "Comma splice after the rain clause",
      }),
    ],
  }),
  micro({
    id: "p-urgent",
    bank: "P",
    domain: "general",
    level: "B1",
    spanish: "«Es urgente», dijo el director.",
    english: '"It is urgent," the director said.',
    acceptables: ['"It is urgent," said the director.', 'The director said, "It is urgent."'],
    traps: [
      trap({
        id: "p-urgent-quotes",
        category: "P",
        weight: 2,
        detector: { kind: "required_pattern", pattern: '"[^"]*[,.]"' },
        comment: "American style puts the comma or period inside the closing quote.",
        ok: '"It is urgent," the director said.',
        no: '"It is urgent", the director said.',
        pitfall: "Comma outside the closing quote",
        label: "Comma outside the quote",
      }),
    ],
  }),
  micro({
    id: "p-raya",
    bank: "P",
    domain: "journalistic",
    level: "B2",
    spanish: "—La cifra es exacta —dijo la ministra.",
    english: '"The figure is exact," the minister said.',
    acceptables: ['"The figure is exact," said the minister.'],
    traps: [
      trap({
        id: "p-raya-dash",
        category: "P",
        weight: 2,
        detector: { kind: "forbidden_pattern", pattern: "[—–]" },
        comment: "The Spanish dialogue dash is not US quotation. Use quotation marks.",
        ok: '"The figure is exact," the minister said.',
        no: "—The figure is exact —said the minister.",
        pitfall: "Spanish raya left in English",
        label: "Dialogue dash instead of quotes",
      }),
      trap({
        id: "p-raya-quotes",
        category: "P",
        weight: 2,
        detector: { kind: "required_pattern", pattern: '"[^"]*[,.]"' },
        comment: "The quoted remark needs US quotes, with the comma inside.",
        ok: '"The figure is exact,"',
        pitfall: "Missing American quotes",
        label: "Quotation marks missing",
      }),
    ],
  }),
  micro({
    id: "p-decimal",
    bank: "P",
    domain: "economic",
    level: "B1",
    spanish: "El índice subió 3,5 puntos.",
    english: "The index rose 3.5 points.",
    acceptables: ["The index went up 3.5 points."],
    traps: [
      trap({
        id: "p-decimal-comma",
        category: "P",
        weight: 2,
        detector: forbid(["3,5"]),
        comment: "A Spanish decimal comma is a US punctuation error here: 3.5 points.",
        ok: "3.5 points",
        no: "3,5 points",
        pitfall: "Spanish decimal comma",
        label: "3,5 vs 3.5",
      }),
      trap({
        id: "p-decimal-present",
        category: "O",
        weight: 4,
        detector: req(["3.5", "3,5"]),
        comment: "The figure is missing.",
        ok: "3.5 points",
        pitfall: "Dropped number",
        label: "3.5 omitted",
      }),
    ],
  }),
  micro({
    id: "p-thousands",
    bank: "P",
    domain: "administrative",
    level: "B2",
    spanish: "El municipio recibió 12.500 solicitudes.",
    english: "The municipality received 12,500 applications.",
    acceptables: ["The city received 12,500 applications.", "The municipality received 12500 applications."],
    traps: [
      trap({
        id: "p-thousands-dot",
        category: "T",
        weight: 8,
        detector: forbid(["12.500"]),
        comment:
          "12.500 in US English is 12.5, not 12,500. The mark looks like punctuation, but the value changed, so it is transfer.",
        ok: "12,500 applications",
        no: "12.500 applications",
        pitfall: "Thousands separator changed the value",
        label: "12.500 read as a decimal",
      }),
      trap({
        id: "p-thousands-present",
        category: "O",
        weight: 8,
        detector: req(["12,500", "12500", "12.500", "twelve thousand five hundred"]),
        comment: "The number of applications is missing.",
        ok: "12,500",
        pitfall: "Dropped number",
        label: "12,500 omitted",
      }),
    ],
  }),
  micro({
    id: "p-serial",
    bank: "P",
    domain: "general",
    level: "B1",
    spanish: "Invitó a Ana, a Luis y a Marta.",
    english: "She invited Ana, Luis, and Marta.",
    acceptables: ["He invited Ana, Luis, and Marta."],
    traps: [
      trap({
        id: "p-serial-comma",
        category: "P",
        weight: 1,
        detector: { kind: "forbidden_pattern", pattern: "\\bLuis\\s+and\\s+Marta\\b", flags: "i" },
        comment: "This session uses the serial comma: Ana, Luis, and Marta. Keep that policy.",
        ok: "Ana, Luis, and Marta",
        no: "Ana, Luis and Marta",
        pitfall: "Missing serial comma",
        label: "Serial comma before and",
      }),
      trap({
        id: "p-serial-ana",
        category: "O",
        weight: 4,
        detector: req(["Ana"]),
        comment: "Ana is missing from the list.",
        ok: "Ana, Luis, and Marta",
        pitfall: "Dropped list item",
        label: "Ana omitted",
      }),
      trap({
        id: "p-serial-luis",
        category: "O",
        weight: 4,
        detector: req(["Luis"]),
        comment: "Luis is missing from the list.",
        ok: "Ana, Luis, and Marta",
        pitfall: "Dropped list item",
        label: "Luis omitted",
      }),
      trap({
        id: "p-serial-marta",
        category: "O",
        weight: 4,
        detector: req(["Marta"]),
        comment: "Marta is missing from the list.",
        ok: "Ana, Luis, and Marta",
        pitfall: "Dropped list item",
        label: "Marta omitted",
      }),
    ],
  }),
  micro({
    id: "p-serial-2",
    bank: "P",
    domain: "general",
    level: "B1",
    spanish: "Compró manzanas, peras y uvas.",
    english: "She bought apples, pears, and grapes.",
    acceptables: ["He bought apples, pears, and grapes."],
    traps: [
      trap({
        id: "p-serial-2-comma",
        category: "P",
        weight: 1,
        detector: { kind: "forbidden_pattern", pattern: "\\bpears\\s+and\\s+grapes\\b", flags: "i" },
        comment: "Keep the serial comma: apples, pears, and grapes.",
        ok: "apples, pears, and grapes",
        no: "apples, pears and grapes",
        pitfall: "Missing serial comma",
        label: "Serial comma in the fruit list",
      }),
    ],
  }),
  micro({
    id: "p-question",
    bank: "P",
    domain: "general",
    level: "B1",
    spanish: '"¿Vienes?", preguntó.',
    english: '"Are you coming?" he asked.',
    acceptables: ['"Are you coming?" she asked.'],
    traps: [
      trap({
        id: "p-question-mark",
        category: "P",
        weight: 2,
        detector: { kind: "required_pattern", pattern: '\\?"' },
        comment: "The question mark goes inside the closing quote.",
        ok: '"Are you coming?" he asked.',
        no: '"Are you coming"? he asked.',
        pitfall: "Question mark outside the quote",
        label: "Question mark outside quotes",
      }),
    ],
  }),
  micro({
    id: "p-currency",
    bank: "P",
    domain: "business",
    level: "B2",
    spanish: "El contrato vale 1.200,50 euros.",
    english: "The contract is worth €1,200.50.",
    acceptables: ["The contract is worth 1,200.50 euros."],
    traps: [
      trap({
        id: "p-currency-form",
        category: "P",
        weight: 4,
        detector: forbid(["1.200,50", "1.200,5"]),
        comment: "US currency writes the thousands comma and the decimal point: €1,200.50.",
        ok: "€1,200.50",
        no: "1.200,50 euros",
        pitfall: "Spanish number format",
        label: "1.200,50 vs 1,200.50",
      }),
      trap({
        id: "p-currency-present",
        category: "O",
        weight: 4,
        detector: req(["1,200.50", "1200.50", "1.200,50"]),
        comment: "The amount is missing.",
        ok: "€1,200.50",
        pitfall: "Dropped number",
        label: "Amount omitted",
      }),
    ],
  }),
  micro({
    id: "p-graph",
    bank: "P",
    domain: "administrative",
    level: "B1",
    spanish: "El informe está listo.\n\nFalta la firma del director.",
    english: "The report is ready.\n\nThe director's signature is still missing.",
    acceptables: ["The report is ready.\n\nThe director's signature is missing."],
    traps: [
      trap({
        id: "p-graph-break",
        category: "P",
        weight: 2,
        detector: { kind: "required_pattern", pattern: "\\n" },
        comment: "The source is two paragraphs. Keep the break.",
        ok: "The report is ready.\\n\\nThe director's signature is still missing.",
        no: "The report is ready. The director's signature is still missing.",
        pitfall: "Paragraph break dropped",
        label: "Paragraphs merged",
      }),
    ],
  }),
  micro({
    id: "p-percent",
    bank: "P",
    domain: "economic",
    level: "B1",
    spanish: "La inflación cerró en 3,2%.",
    english: "Inflation ended the year at 3.2%.",
    acceptables: ["Inflation closed the year at 3.2 percent."],
    traps: [
      trap({
        id: "p-percent-comma",
        category: "P",
        weight: 2,
        detector: forbid(["3,2"]),
        comment: "Write 3.2%, with a point, not 3,2%.",
        ok: "3.2%",
        no: "3,2%",
        pitfall: "Spanish decimal comma",
        label: "3,2% vs 3.2%",
      }),
      trap({
        id: "p-percent-present",
        category: "O",
        weight: 4,
        detector: req(["3.2", "3,2"]),
        comment: "The percent is missing.",
        ok: "3.2%",
        pitfall: "Dropped number",
        label: "3.2% omitted",
      }),
    ],
  }),
  micro({
    id: "p-splice-2",
    bank: "P",
    domain: "general",
    level: "B2",
    spanish: "El informe llegó tarde, el director canceló la reunión.",
    english: "The report arrived late, so the director canceled the meeting.",
    acceptables: [
      "The report arrived late; the director canceled the meeting.",
      "The report arrived late. The director canceled the meeting.",
    ],
    traps: [
      trap({
        id: "p-splice-2-hit",
        category: "P",
        weight: 2,
        detector: { kind: "forbidden_pattern", pattern: "\\blate,\\s+the director\\b", flags: "i" },
        comment: "late, the director is a comma splice. Add so, or start a new sentence.",
        ok: "The report arrived late, so the director canceled the meeting.",
        no: "The report arrived late, the director canceled the meeting.",
        pitfall: "Comma splice",
        label: "Comma splice before the director",
      }),
    ],
  }),

  micro({
    id: "u-hereby",
    bank: "U",
    domain: "administrative",
    level: "C1",
    spanish: "Por la presente se notifica que la solicitud ha sido denegada.",
    english: "This notice confirms that the application has been denied.",
    acceptables: [
      "The application has been denied.",
      "We are writing to tell you that the application has been denied.",
    ],
    traps: [
      trap({
        id: "u-hereby-register",
        category: "U",
        weight: 4,
        detector: forbid(["hereby", "be it known", "pursuant"]),
        comment:
          "The translation instructions for this notice want plain US prose. hereby / pursuant is stiff legalese the source does not require.",
        ok: "This notice confirms that the application has been denied.",
        no: "You are hereby notified that the application has been denied.",
        pitfall: "Stiff legalese",
        label: "hereby / pursuant register",
      }),
      trap({
        id: "u-hereby-denied",
        category: "O",
        weight: 4,
        detector: req(["denied", "rejected", "turned down"]),
        comment: "denegada has to come through as denied or rejected.",
        ok: "has been denied",
        pitfall: "Dropped outcome",
        label: "denegada omitted",
      }),
    ],
  }),
  micro({
    id: "u-libreria",
    bank: "U",
    domain: "general",
    level: "B1",
    spanish: "La librería abre a las nueve.",
    english: "The bookstore opens at nine.",
    acceptables: ["The bookshop opens at nine.", "The bookstore opens at 9."],
    traps: [
      trap({
        id: "u-libreria-cognate",
        category: "T",
        weight: 4,
        detector: { kind: "forbidden_pattern", pattern: "\\blibrary\\b", flags: "i" },
        comment: "librería is a bookstore. library is biblioteca.",
        ok: "The bookstore opens at nine.",
        no: "The library opens at nine.",
        pitfall: "False friend librería",
        label: "librería rendered as library",
        lemma: "librería",
      }),
      trap({
        id: "u-libreria-present",
        category: "O",
        weight: 4,
        detector: req(["bookstore", "bookshop", "library"]),
        comment: "The place that opens is missing.",
        ok: "the bookstore",
        pitfall: "Dropped subject",
        label: "librería omitted",
        lemma: "librería",
      }),
    ],
  }),
  micro({
    id: "u-asistir",
    bank: "U",
    domain: "general",
    level: "B1",
    spanish: "Los concejales asistieron a la sesión.",
    english: "The council members attended the session.",
    acceptables: ["The councilors attended the meeting.", "Council members were at the session."],
    traps: [
      trap({
        id: "u-asistir-cognate",
        category: "T",
        weight: 4,
        detector: { kind: "forbidden_pattern", pattern: "\\bassisted\\b", flags: "i" },
        comment: "asistir a una sesión means attended. assisted means helped.",
        ok: "attended the session",
        no: "assisted the session",
        pitfall: "False friend asistir",
        label: "asistir rendered as assist",
        lemma: "asistir",
      }),
      trap({
        id: "u-asistir-present",
        category: "O",
        weight: 4,
        detector: req(["attended", "were at", "assisted", "went to"]),
        comment: "The attendance is missing.",
        ok: "attended the session",
        pitfall: "Dropped verb",
        label: "asistieron omitted",
        lemma: "asistir",
      }),
    ],
  }),
];

function sentence(spec: {
  id: string;
  spanish: string;
  english: string;
  acceptables?: string[];
  traps: Trap[];
}): SentenceItem {
  return spec;
}

const passageSentences: SentenceItem[] = [
  sentence({
    id: "med-1",
    spanish:
      "El alcalde de Medellín, Federico Gutiérrez, presentó el 14 de marzo de 2023 un plan de 50,3 millones de dólares para el transporte público.",
    english:
      "Medellín Mayor Federico Gutiérrez on March 14, 2023, presented a $50.3 million plan for public transportation.",
    acceptables: [
      "On March 14, 2023, Medellín Mayor Federico Gutiérrez presented a $50.3 million plan for public transportation.",
    ],
    traps: [
      trap({
        id: "med-1-mayor",
        category: "SP",
        weight: 2,
        detector: caps(["mayor Federico"]),
        comment: "Mayor before the name is capitalized.",
        ok: "Mayor Federico Gutiérrez",
        no: "mayor Federico Gutiérrez",
        pitfall: "Lowercase title before a name",
        label: "Mayor vs mayor",
      }),
      trap({
        id: "med-1-name",
        category: "O",
        weight: 8,
        detector: req(["Gutiérrez", "Gutierrez"]),
        comment: "The mayor's name is missing.",
        ok: "Federico Gutiérrez",
        pitfall: "Dropped name",
        label: "Gutiérrez omitted",
        lemma: "Gutiérrez",
      }),
      trap({
        id: "med-1-decimal",
        category: "P",
        weight: 2,
        detector: forbid(["50,3"]),
        comment: "Write $50.3 million, not 50,3.",
        ok: "$50.3 million",
        no: "50,3 million dollars",
        pitfall: "Spanish decimal comma",
        label: "50,3 vs 50.3",
      }),
      trap({
        id: "med-1-amount",
        category: "O",
        weight: 4,
        detector: req(["50.3", "50,3"]),
        comment: "The investment figure is missing.",
        ok: "$50.3 million",
        pitfall: "Dropped number",
        label: "50.3 million omitted",
      }),
      trap({
        id: "med-1-date",
        category: "O",
        weight: 4,
        detector: req(["2023"]),
        comment: "The presentation date's year is missing.",
        ok: "March 14, 2023",
        pitfall: "Dropped date",
        label: "March 14, 2023 year omitted",
      }),
    ],
  }),
  sentence({
    id: "med-2",
    spanish:
      '"La situación es crítica", declaró, "pero la ciudad puede responder si hay un compromiso con la vida de los pasajeros".',
    english:
      '"The situation is critical," he declared, "but the city can respond if there is a commitment to the lives of the passengers."',
    acceptables: [
      '"The situation is critical," he said, "but the city can respond if there is a commitment to passengers\' lives."',
    ],
    traps: [
      trap({
        id: "med-2-quotes",
        category: "P",
        weight: 2,
        detector: { kind: "required_pattern", pattern: '"[^"]*,"' },
        comment: "The comma belongs inside the quotes: \"critical,\" he declared.",
        ok: '"The situation is critical," he declared',
        no: '"The situation is critical", he declared',
        pitfall: "Comma outside the closing quote",
        label: "American quotes",
      }),
      trap({
        id: "med-2-pos",
        category: "T",
        weight: 4,
        detector: {
          kind: "pos_job",
          job: "noun",
          accept: ["commitment"],
          reject: ["committed", "committing"],
        },
        comment: "compromiso con la vida is a noun. Committed to the lives of the passengers changes the job.",
        ok: "a commitment to the lives of the passengers",
        no: "Committed to the lives of the passengers",
        pitfall: "POS drift on noun heads",
        label: "compromiso as Committed",
        lemma: "compromiso",
      }),
      trap({
        id: "med-2-head",
        category: "O",
        weight: 4,
        detector: req(["commitment", "committed", "committing", "pledge"]),
        comment: "compromiso is missing from the quotation.",
        ok: "a commitment to the lives of the passengers",
        pitfall: "Dropped noun head",
        label: "compromiso omitted",
        lemma: "compromiso",
      }),
    ],
  }),
  sentence({
    id: "med-3",
    spanish:
      "El plan incluye tres medidas: ampliar la red de buses, renovar 120 estaciones y contratar 1.250 conductores antes de diciembre de 2024.",
    english:
      "The plan includes three measures: expanding the bus network, renovating 120 stations, and hiring 1,250 drivers before December 2024.",
    traps: [
      trap({
        id: "med-3-serial",
        category: "P",
        weight: 1,
        detector: { kind: "forbidden_pattern", pattern: "\\bstations\\s+and\\s+hiring\\b", flags: "i" },
        comment: "Keep the serial comma in the three-part list.",
        ok: "renovating 120 stations, and hiring 1,250 drivers",
        no: "renovating 120 stations and hiring 1,250 drivers",
        pitfall: "Missing serial comma",
        label: "Serial comma in the three measures",
      }),
      trap({
        id: "med-3-1250",
        category: "T",
        weight: 8,
        detector: forbid(["1.250"]),
        comment: "1.250 in English is not 1,250. The number of drivers changes.",
        ok: "1,250 drivers",
        no: "1.250 drivers",
        pitfall: "Thousands separator changed the value",
        label: "1.250 drivers",
      }),
      trap({
        id: "med-3-1250-present",
        category: "O",
        weight: 8,
        detector: req(["1,250", "1250", "1.250"]),
        comment: "The number of drivers is missing.",
        ok: "1,250 drivers",
        pitfall: "Dropped number",
        label: "1,250 drivers omitted",
      }),
      trap({
        id: "med-3-120",
        category: "O",
        weight: 4,
        detector: req(["120"]),
        comment: "The 120 stations are missing.",
        ok: "120 stations",
        pitfall: "Dropped number",
        label: "120 stations omitted",
      }),
      trap({
        id: "med-3-buses",
        category: "O",
        weight: 4,
        detector: req(["bus"]),
        comment: "The bus network is one of the three measures.",
        ok: "expanding the bus network",
        pitfall: "Dropped list item",
        label: "Bus network omitted",
      }),
      trap({
        id: "med-3-year",
        category: "O",
        weight: 2,
        detector: req(["2024"]),
        comment: "diciembre de 2024 is missing.",
        ok: "before December 2024",
        pitfall: "Dropped date",
        label: "December 2024 omitted",
      }),
    ],
  }),
  sentence({
    id: "med-4",
    spanish: "Incluso los barrios más alejados entrarían en la primera fase.",
    english: "Even the most distant neighborhoods would be included in the first phase.",
    acceptables: ["The most outlying neighborhoods would also enter the first phase."],
    traps: [
      trap({
        id: "med-4-incluso",
        category: "O",
        weight: 2,
        detector: req(["even", "also", "too"]),
        comment: "incluso is doing work. Even / also has to stay.",
        ok: "Even the most distant neighborhoods",
        no: "The most distant neighborhoods would be included in the first phase.",
        pitfall: "Dropped intensifier",
        label: "incluso dropped",
        lemma: "incluso",
      }),
    ],
  }),
  sentence({
    id: "med-5",
    spanish: "Según el artículo 12 del acuerdo municipal, el Concejo debe votar la iniciativa el 5 de abril.",
    english: "Under Article 12 of the municipal agreement, the Council must vote on the initiative on April 5.",
    traps: [
      trap({
        id: "med-5-article",
        category: "SP",
        weight: 2,
        detector: caps(["article 12"]),
        comment: "Article 12 capitalizes Article.",
        ok: "Article 12",
        no: "article 12",
        pitfall: "Legal-citation caps",
        label: "Article vs article",
      }),
      trap({
        id: "med-5-number",
        category: "O",
        weight: 4,
        detector: req(["12"]),
        comment: "Article 12's number is missing.",
        ok: "Article 12",
        pitfall: "Dropped number",
        label: "Article 12 omitted",
      }),
      trap({
        id: "med-5-april",
        category: "O",
        weight: 2,
        detector: req(["April", "abril"]),
        comment: "The April vote date is missing.",
        ok: "on April 5",
        pitfall: "Dropped date",
        label: "April 5 omitted",
      }),
      trap({
        id: "med-5-concejo",
        category: "U",
        weight: 2,
        detector: forbid(["Concejo"]),
        comment: "Concejo in an English sentence leaves the Spanish body name untranslated. Use Council.",
        ok: "the Council",
        no: "the Concejo",
        pitfall: "Spanish body name left in English",
        label: "Concejo left in English",
      }),
    ],
  }),
  sentence({
    id: "med-6",
    spanish:
      "La secretaria de Movilidad, Ana Pérez, dijo que la tarifa no subirá por encima del 3,2% y que el proyecto no reemplaza al metro.",
    english:
      "Mobility Secretary Ana Pérez said the fare will not rise by more than 3.2% and that the project does not replace the metro.",
    acceptables: [
      "Secretary of Mobility Ana Pérez said the fare will not increase by more than 3.2% and that the project will not replace the metro.",
    ],
    traps: [
      trap({
        id: "med-6-secretary",
        category: "SP",
        weight: 2,
        detector: caps(["secretary Ana"]),
        comment: "Secretary before Ana Pérez is capitalized.",
        ok: "Secretary Ana Pérez",
        no: "secretary Ana Pérez",
        pitfall: "Lowercase title before a name",
        label: "Secretary vs secretary",
      }),
      trap({
        id: "med-6-name",
        category: "O",
        weight: 8,
        detector: req(["Pérez", "Perez"]),
        comment: "Ana Pérez is missing.",
        ok: "Ana Pérez",
        pitfall: "Dropped name",
        label: "Ana Pérez omitted",
        lemma: "Pérez",
      }),
      trap({
        id: "med-6-percent",
        category: "P",
        weight: 2,
        detector: forbid(["3,2"]),
        comment: "Write 3.2%, not 3,2%.",
        ok: "3.2%",
        no: "3,2%",
        pitfall: "Spanish decimal comma",
        label: "3,2% decimal",
      }),
      trap({
        id: "med-6-percent-present",
        category: "O",
        weight: 4,
        detector: req(["3.2", "3,2"]),
        comment: "The 3.2% cap is missing.",
        ok: "3.2%",
        pitfall: "Dropped number",
        label: "3.2% omitted",
      }),
      trap({
        id: "med-6-polarity",
        category: "T",
        weight: 8,
        detector: { kind: "forbidden_pattern", pattern: "\\bfare will rise\\b|\\bfare will increase\\b", flags: "i" },
        comment: "no subirá is negative. the fare will rise flips it.",
        ok: "the fare will not rise by more than 3.2%",
        no: "the fare will rise by more than 3.2%",
        pitfall: "Polarity flip",
        label: "no subirá flipped",
      }),
    ],
  }),
  sentence({
    id: "med-7",
    spanish: "Advirtió que sin el apoyo de la comunidad la obra se retrasaría.",
    english: "She warned that without community support the work would be delayed.",
    acceptables: ["She warned that without the community's support the project would be delayed."],
    traps: [
      trap({
        id: "med-7-apoyo",
        category: "O",
        weight: 4,
        detector: req(["support", "backing"]),
        comment: "apoyo de la comunidad is missing.",
        ok: "without community support",
        pitfall: "Dropped noun head",
        label: "apoyo omitted",
        lemma: "apoyo",
      }),
    ],
  }),
  sentence({
    id: "med-8",
    spanish: "El Banco de la República no financia el plan; los recursos salen del presupuesto local.",
    english: "The Bank of the Republic does not finance the plan; the funds come from the local budget.",
    acceptables: ["Colombia's central bank does not finance the plan; the money comes from the local budget."],
    traps: [
      trap({
        id: "med-8-splice",
        category: "P",
        weight: 2,
        detector: { kind: "forbidden_pattern", pattern: "\\bplan,\\s+the funds\\b", flags: "i" },
        comment: "The Spanish semicolon should not become a comma splice in English.",
        ok: "does not finance the plan; the funds come from the local budget.",
        no: "does not finance the plan, the funds come from the local budget.",
        pitfall: "Comma splice",
        label: "Comma splice after plan",
      }),
      trap({
        id: "med-8-polarity",
        category: "T",
        weight: 8,
        detector: { kind: "forbidden_pattern", pattern: "\\bdoes finance the plan\\b|\\bwill finance the plan\\b", flags: "i" },
        comment: "no financia is negative.",
        ok: "does not finance the plan",
        no: "does finance the plan",
        pitfall: "Polarity flip",
        label: "no financia flipped",
      }),
      trap({
        id: "med-8-caps",
        category: "SP",
        weight: 1,
        detector: caps(["bank of the republic"]),
        comment: "Bank of the Republic is the institution's English name here, so the main words are capitalized.",
        ok: "the Bank of the Republic",
        no: "the bank of the republic",
        pitfall: "Institution caps",
        label: "Bank of the Republic caps",
      }),
    ],
  }),
  sentence({
    id: "med-9",
    spanish:
      "Usuarios pidieron publicar el estudio completo (incluyendo los anexos técnicos) y evitar alternativas en la redacción final.",
    english:
      "Users asked that the full study be published (including the technical annexes) and that no alternatives be left in the final wording.",
    traps: [
      trap({
        id: "med-9-annex",
        category: "O",
        weight: 2,
        detector: req(["annexes"]),
        comment: "The parenthetical anexos técnicos is missing.",
        ok: "(including the technical annexes)",
        pitfall: "Dropped parenthetical",
        label: "Technical annexes dropped",
      }),
      trap({
        id: "med-9-study",
        category: "O",
        weight: 4,
        detector: req(["study"]),
        comment: "The study they want published is missing.",
        ok: "the full study",
        pitfall: "Dropped object",
        label: "estudio omitted",
      }),
    ],
  }),
  sentence({
    id: "med-10",
    spanish: "La protección de los datos de los pasajeros, señalaron, es tan urgente como la compra de los vehículos.",
    english: "The protection of passenger data, they noted, is as urgent as buying the vehicles.",
    acceptables: ["Protection of passenger data, they noted, is as urgent as the purchase of the vehicles."],
    traps: [
      trap({
        id: "med-10-pos",
        category: "T",
        weight: 4,
        detector: {
          kind: "pos_job",
          job: "noun",
          accept: ["protection"],
          reject: ["protecting"],
        },
        comment: "protección is a noun. Protecting passenger data changes the job.",
        ok: "The protection of passenger data",
        no: "Protecting passenger data, they noted, is as urgent as buying the vehicles.",
        pitfall: "POS drift on noun heads",
        label: "protección rendered as protecting",
        lemma: "protección",
      }),
      trap({
        id: "med-10-vehicles",
        category: "O",
        weight: 4,
        detector: req(["vehicles"]),
        comment: "The comparison with the purchase of the vehicles is missing.",
        ok: "as urgent as buying the vehicles",
        pitfall: "Dropped comparison",
        label: "vehículos omitted",
      }),
    ],
  }),
  sentence({
    id: "med-11",
    spanish:
      "Un vocero añadió que la ciudad necesita un compromiso claro, no un eslogan, y que la falta de mantenimiento dejó 40 buses fuera de servicio en enero de 2023.",
    english:
      "A spokesperson added that the city needs a clear commitment, not a slogan, and that poor maintenance had already taken 40 buses out of service in January 2023.",
    traps: [
      trap({
        id: "med-11-pos",
        category: "T",
        weight: 4,
        detector: {
          kind: "pos_job",
          job: "noun",
          accept: ["commitment"],
          reject: ["committed"],
        },
        comment: "un compromiso claro is a noun phrase. a clear committed changes the job.",
        ok: "a clear commitment",
        no: "clearly committed",
        pitfall: "POS drift on noun heads",
        label: "compromiso claro as committed",
        lemma: "compromiso",
      }),
      trap({
        id: "med-11-40",
        category: "O",
        weight: 4,
        detector: req(["40"]),
        comment: "The 40 buses are missing.",
        ok: "40 buses",
        pitfall: "Dropped number",
        label: "40 buses omitted",
      }),
      trap({
        id: "med-11-jan",
        category: "SP",
        weight: 1,
        detector: caps(["january"]),
        comment: "January is capitalized.",
        ok: "January 2023",
        no: "january 2023",
        pitfall: "Month caps",
        label: "January capitalization",
      }),
    ],
  }),
  sentence({
    id: "med-12",
    spanish:
      "El Concejo había rechazado una versión anterior en noviembre de 2022 porque omitía el costo de las estaciones nuevas.",
    english:
      "The Council had rejected an earlier version in November 2022 because it omitted the cost of the new stations.",
    traps: [
      trap({
        id: "med-12-year",
        category: "O",
        weight: 4,
        detector: req(["2022"]),
        comment: "November 2022 is missing.",
        ok: "November 2022",
        pitfall: "Dropped date",
        label: "2022 omitted",
      }),
      trap({
        id: "med-12-polarity",
        category: "T",
        weight: 8,
        detector: { kind: "forbidden_pattern", pattern: "\\bhad approved\\b", flags: "i" },
        comment: "había rechazado is negative. had approved flips the earlier vote.",
        ok: "had rejected an earlier version",
        no: "had approved an earlier version",
        pitfall: "Polarity flip",
        label: "rechazado flipped to approved",
      }),
      trap({
        id: "med-12-council",
        category: "SP",
        weight: 1,
        detector: caps(["the council"]),
        comment: "Council as this body is capitalized.",
        ok: "The Council",
        no: "the council",
        pitfall: "Body caps",
        label: "Council capitalization",
      }),
    ],
  }),
  sentence({
    id: "med-13",
    spanish:
      "Gutiérrez insistió en que el proyecto actual no aumenta el endeudamiento por encima del límite legal y que los contratos se publicarán completos.",
    english:
      "Gutiérrez insisted that the current project does not raise the debt above the legal limit and that the contracts will be published in full.",
    acceptables: [
      "Gutierrez insisted that the current project does not increase borrowing above the legal limit and that the contracts will be published in full.",
    ],
    traps: [
      trap({
        id: "med-13-name",
        category: "O",
        weight: 4,
        detector: req(["Gutiérrez", "Gutierrez"]),
        comment: "Gutiérrez, the speaker, is missing.",
        ok: "Gutiérrez insisted",
        pitfall: "Dropped name",
        label: "Gutiérrez omitted",
        lemma: "Gutiérrez",
      }),
      trap({
        id: "med-13-polarity",
        category: "T",
        weight: 8,
        detector: { kind: "forbidden_pattern", pattern: "\\bdoes raise the debt\\b|\\bwill raise the debt\\b", flags: "i" },
        comment: "no aumenta el endeudamiento is negative.",
        ok: "does not raise the debt",
        no: "does raise the debt",
        pitfall: "Polarity flip",
        label: "no aumenta flipped",
      }),
      trap({
        id: "med-13-contracts",
        category: "O",
        weight: 2,
        detector: req(["contracts"]),
        comment: "The promise to publish the contracts is missing.",
        ok: "the contracts will be published in full",
        pitfall: "Dropped clause",
        label: "contratos omitted",
      }),
    ],
  }),
  sentence({
    id: "med-14",
    spanish:
      '"No vamos a esconder las cifras", dijo, aunque evitó decir qué pasará si el tope del 3,2% resulta insuficiente.',
    english:
      '"We are not going to hide the figures," he said, although he avoided specifying what happens if the 3.2% cap proves too low given inflation.',
    traps: [
      trap({
        id: "med-14-quotes",
        category: "P",
        weight: 2,
        detector: { kind: "required_pattern", pattern: '"[^"]*,"' },
        comment: "Comma inside the closing quote.",
        ok: '"We are not going to hide the figures," he said',
        no: '"We are not going to hide the figures", he said',
        pitfall: "Comma outside the closing quote",
        label: "American quotes",
      }),
      trap({
        id: "med-14-percent",
        category: "P",
        weight: 2,
        detector: forbid(["3,2"]),
        comment: "Write 3.2%, not 3,2%.",
        ok: "3.2%",
        no: "3,2%",
        pitfall: "Spanish decimal comma",
        label: "3,2% decimal",
      }),
      trap({
        id: "med-14-hide",
        category: "T",
        weight: 8,
        detector: { kind: "forbidden_pattern", pattern: "\\bare going to hide\\b", flags: "i" },
        comment: "No vamos a esconder is negative. We are going to hide the figures flips it.",
        ok: "We are not going to hide the figures",
        no: "We are going to hide the figures",
        pitfall: "Polarity flip",
        label: "no vamos a esconder flipped",
      }),
    ],
  }),
];

function buildPassage(sentences: SentenceItem[]): PassageItem {
  const spanish = sentences.map((s) => s.spanish).join(" ");
  const english = sentences.map((s) => s.english).join(" ");
  const traps = sentences.flatMap((s) => s.traps);
  return {
    id: "passage-medellin",
    mode: "passage",
    title: "Medellín transit plan",
    spanish,
    english,
    domain: "journalistic",
    wordCount: wordCount(spanish),
    translationInstructions: {
      sourceMedium: "Newspaper feature, Medellín",
      targetMedium: "US English newspaper brief",
      purpose: "Tell a US reader what the city proposed, with the figures and the limits intact",
      audience: "General readers of a national US paper who do not know the city administration",
    },
    sentences,
    focus: [...new Set(traps.map((t) => t.pitfall))],
    errors_to_catch: traps.map((t) => t.label),
  };
}

export const PASSAGE: PassageItem = buildPassage(passageSentences);

export function bankCounts() {
  const counts: Record<string, number> = {};
  for (const item of MICROS) counts[item.bank] = (counts[item.bank] ?? 0) + 1;
  return counts;
}

export function validateContent(): void {
  const problems: string[] = [];
  for (const item of MICROS) {
    const focus = [...new Set(item.traps.map((t) => t.pitfall))];
    if (focus.join("|") !== item.focus.join("|")) problems.push(`${item.id} focus drifted`);
    if (item.errors_to_catch.join("|") !== item.traps.map((t) => t.label).join("|")) {
      problems.push(`${item.id} errors_to_catch drifted`);
    }
    for (const t of item.traps) {
      if ((t.category === "P" || t.category === "SP") && t.weightIfMissed > 4) {
        problems.push(`${t.id} mechanical weight ${t.weightIfMissed}`);
      }
    }
    const grade = gradeItem(item, item.english, { mode: "micro" });
    if (grade.points !== 0) {
      problems.push(`${item.id} key scored ${grade.points} (${grade.fired.map((f) => f.trapId + ":" + f.code).join(", ")})`);
    }
    for (const alt of item.acceptables ?? []) {
      const g = gradeItem(item, alt, { mode: "micro" });
      if (g.points !== 0) problems.push(`${item.id} acceptable scored ${g.points}: ${alt}`);
    }
  }
  const counts = bankCounts();
  for (const bank of ["O", "P", "POS"] as Bank[]) {
    if ((counts[bank] ?? 0) < 10) problems.push(`bank ${bank} has ${counts[bank] ?? 0}`);
  }
  if (PASSAGE.wordCount < 225 || PASSAGE.wordCount > 275) {
    problems.push(`passage word count ${PASSAGE.wordCount}`);
  }
  const pieces = splitEnglishSentences(PASSAGE.english);
  if (pieces.length !== PASSAGE.sentences.length) {
    problems.push(`passage split ${pieces.length} != ${PASSAGE.sentences.length}`);
  }
  for (const s of PASSAGE.sentences) {
    const g = gradeItem(s, s.english, { mode: "sentence", builtins: false });
    if (g.points !== 0) problems.push(`${s.id} key scored ${g.points} (${g.fired.map((f) => f.trapId).join(",")})`);
  }
  const whole = gradePassage(PASSAGE, PASSAGE.english);
  if (whole.points !== 0) {
    problems.push(`passage key scored ${whole.points} (${whole.fired.map((f) => f.trapId).join(",")})`);
  }
  if (problems.length) {
    throw new Error(`Drill content invalid:\n${problems.join("\n")}`);
  }
}

validateContent();

export function getMicro(id: string): DrillItem | undefined {
  return MICROS.find((m) => m.id === id);
}

const BANK_FOR_CATEGORY: Partial<Record<ErrorCat, Bank>> = {
  O: "O",
  P: "P",
  T: "POS",
  SP: "titles",
  U: "U",
  SYN: "POS",
  G: "P",
  A: "O",
  IND: "P",
};

export function selectMicros(opts: {
  bank?: string;
  count: number;
  itemId?: string;
  heat: Record<string, number>;
  weakest?: ErrorCat;
  todayTrapIds?: string[];
  todayPitfalls?: string[];
  todayLemmas?: string[];
  todayCategories?: ErrorCat[];
}): DrillItem[] {
  if (opts.itemId) {
    const one = getMicro(opts.itemId);
    return one ? [one] : [];
  }
  let pool = MICROS.slice();
  const bank = opts.bank;
  if (bank === "O" || bank === "P" || bank === "POS" || bank === "titles" || bank === "U") {
    pool = pool.filter((m) => m.bank === bank);
  } else if (bank === "weak") {
    const cat = opts.weakest ?? "O";
    const preferred = BANK_FOR_CATEGORY[cat] ?? "O";
    const tagged = pool.filter((m) => m.traps.some((t) => t.category === cat) || m.bank === preferred);
    pool = tagged.length ? tagged : pool.filter((m) => m.bank === preferred);
  } else if (bank === "today") {
    const ids = new Set(opts.todayTrapIds ?? []);
    const pitfalls = new Set(opts.todayPitfalls ?? []);
    const lemmas = new Set((opts.todayLemmas ?? []).filter(Boolean));
    const cats = new Set(opts.todayCategories ?? []);
    const matched = pool.filter((m) =>
      m.traps.some(
        (t) =>
          ids.has(t.id) ||
          pitfalls.has(t.pitfall) ||
          (!!t.lemma && lemmas.has(t.lemma)) ||
          cats.has(t.category)
      )
    );
    pool = matched.length ? matched : pool.filter((m) => m.bank === (BANK_FOR_CATEGORY[opts.weakest ?? "O"] ?? "O"));
  }
  const ranked = pool
    .map((item) => ({
      item,
      heat: item.traps.reduce((sum, t) => sum + (opts.heat[t.id] ?? 0), 0),
    }))
    .sort((a, b) => b.heat - a.heat || a.item.id.localeCompare(b.item.id));
  return ranked.slice(0, opts.count).map((r) => r.item);
}
